= 3scape Progress Document
Ancient Yaks
v1.4.1, 2018-10-22

:icons: font
// tłumaczenia
:toc-title: Spis Treści
:version-label: Wersja

== Obecne założenia gry

3scape jest zręcznościowo-logiczną grą platformową.

Wcielamy się w grupę trzech bohaterów, którzy tylko dzięki swoim połączonym zdolnościom są w stanie pokonywać kolejne przeszkody:

* wojownik - dysponuje on siłą, która okaże się nieoceninia nie tylko przy walce z wrogimi istotami czy niszczeniem przeszkód na drodze,
* łotrzyk - zwinne palce, spryt, zręczność czy umiejętność strzelania z łuku będą niezwykle przydatne podczas przemierzania świata pełnego zasadzek i pułapek, 
* czarodziej - wiedza oraz zdolności magiczne będą niejednokrotnie jedyną opcją ratunku dla naszych bohaterów.

Bohaterowie podróżują razem, idąc jeden za drugim. W zależności od ich ustawienia w rzędzie, dysponują oni innymi umiejętnościami, które potrafią oddziaływać ze sobą w najróżniejszy sposób. Dobre przetasowywanie naszej drużyny to klucz do sukcesu w 3scape.

== Podział pracy

Poniżej przedstawiamy podział obowiązków na najbliższy okres dwóch tygodni (tydzień 6).

==== Cały zespół

* [ ] Wymyślanie umiejętności/zdolności/mocy dla naszych bohaterów.
* [ ] Level design - w jaki sposób mają wyglądać nasze poziomy, w jaki sposób gracz może się wykazać logiką, a w jaki zręcznością.
* [ ] Przemyślenie sterowania - w jaki dokładnie sposób będziemy sterować naszymi bohaterami, korzystać z ich umiejętności, zmieniać ich kolejność w rzędzie.

==== Krzysiek

* [ ] Dopracowanie kolizji bohaterów.
*     _W przypadku kiedy jeden bohater nie będzie mógł iść (np. trafi na przeszkodę przed sobą) każdy z bohaterów się zatrzyma i bohaterowie nie będą na siebie nachodzić._
* [ ] Implementacja umiejętności maga - ochronne pole.
*     _Jest to jeden z naszych pierwszych pomysłów na umiejętność, z którego wdrożeniem czekamy na uporządkowanie kodu (niżej)._

==== Justyna

* [ ] Praca nad poziomem tutorialowym/prototypowym - wprowadzanie prostych przeszkód pozwalających pokazać zdolności bohaterów.
*     _Poziom nad którym pracujemy jako prototyp chcemy w przyszłości przekształcić w pierwszy poziom/tutorial, gdzie gracze nauczą się jak korzystać ze zdolności naszych bohaterów. Do tego jednak jeszcze daleko, co nie zmniejsza jego roli. Poziom ten trzeba rozwijać by pokazywać nowe możliwości w grze, jakie udało nam się zaimplementować._ 
* [ ] Implementacja umiejętności łotrzyka - zastawianie pułapek.
*     _Jest to jeden z naszych pierwszych pomysłów na umiejętność, z którego wdrożeniem czekamy na uporządkowanie kodu (niżej)._ 

==== Bartek

* [ ] Poprawa modelów postaci w grze.
*     _W tym momencie nie przejmujemy się dokładnym wyglądem naszej produkcji. O ile gra nie musi być ładna, tak wypadałoby by modele (oraz ich animacje) zachowywały się w taki sam sposób, pasowały do swoich colliderów, nie działąły z opóźnieniem czy demonstowały to co robią._ 
* [ ] Implementacja umiejętności wojownika - podnoszenie kompanów.
*     _Jest to jeden z naszych pierwszych pomysłów na umiejętność, z którego wdrożeniem czekamy na uporządkowanie kodu (niżej)._ 

==== Karol

* [ ] Doprowadznie kodu do porządku, narzucenie nazwewnictwa zmiennych oraz klas, uporządkowanie plików (głównie scen).
*     _Początkowo, nasza praca nie była tak dobrze zorganizowana jak byśmy chcieli. Dla wszystkich był to początek zabawy w Unity, przez co skupiliśmy się bardziej na poznaniu silnika niż na porządku w projekcie. Dopóki więcej rzeczy wciąż mamy w głowie niż w komputerach należy uporządkować nasz projekt._
* [ ] Implementacja umiejętności łotrzyka - rozbrajanie pułapek.
*     _Jest to jeden z naszych pierwszych pomysłów na umiejętność, z którego wdrożeniem czekamy na uporządkowanie kodu._ 

==== Potencjalna nowa osoba w zespole

* [ ] Przedstawienie swojej opini dotyczącej planowanych mechanik w grze oraz sugestii dotyczących ich rozwoju.
*     _Nowa osoba pozwoli wprowadzić swieżość do zespołu. Niewykorzystane pomysły w swojej poprzedniej grze będzie mogła przenieść do nowej produkcji, a swoją dozę kreatywności wykorzystać w zupełnie innych realiach. Ważne jest dla nas, by poznać opinię dotyczącą tego co już jest w grze i co planujemy do niej dodać._
* [ ] Implementacja umiejętności, którą uznamy za najpotrzebniejszą w tym momencie.
*     _Po burzy mózgów na pewno uda nam się wymyślić nowe umiejętności. Najważniejsza z nich zostanie zaimplementowa przez nowego członka (lub osobę, która boryka się z problemem zbyt dużej ilości wolnego czasu)._

==== Dodatkowe zadania

Tutaj wypisaliśmy rzeczy, które kiedyś koniecznie chcemy wprowadzić do gry, jednak ciężko powiedzieć kiedy uda nam się nimi zająć.

* [ ] Menu gry.
* [ ] Pasek umiejętności bohaterów.
*     _W zależności od pozycji danego bohatera w rzędzie, dysponuje on innymi umiejętnościami. By ułatwić rozgrywkę, w dolnej części ekranu będzie wyświetlony pasek z ikonami umiejętności dla każdego bohatera. Gracz zarówno będzie miał podpowiedź do jakich umiejętności w tym momencie ma dostęp, oraz jaki klawisz pozwala skorzystać z jakiej umiejętności._