= 3scape - przegląd i planowanie sprintu: *Tydzień 10*
Ancient Yaks
0.10.1, 2018-12-04
:toc:
:toc-title: Spis Treści
:version-label: Wersja
:icons: font

== Obecne założenia gry

3scape jest zręcznościowo-logiczną grą platformową, która działa na silniku Unity.

Wcielamy się w grupę trzech bohaterów, którzy tylko dzięki swoim połączonym zdolnościom są w stanie pokonywać kolejne przeszkody:

* wojownik - dysponuje on siłą, która okaże się nieoceniona nie tylko przy walce z wrogimi istotami czy niszczeniem przeszkód na drodze,
* łotrzyk - zwinne palce, spryt, zręczność czy umiejętność strzelania z łuku będą niezwykle przydatne podczas przemierzania świata pełnego zasadzek i pułapek, 
* czarodziej - wiedza oraz zdolności magiczne będą niejednokrotnie jedyną opcją ratunku dla naszych bohaterów.

Bohaterowie podróżują razem, idąc jeden za drugim. W zależności od ich ustawienia w rzędzie, dysponują oni innymi umiejętnościami, które potrafią oddziaływać ze sobą w najróżniejszy sposób. Dobre przetasowywanie naszej drużyny to klucz do sukcesu w 3scape.

=== Sterowanie

* Poruszamy się bohaterami za pomocą klawiszy *W A D*, bądź *strzałek*.
* Zmieniamy kolejność bohaterów za pomocą klawisza *Cudzysłów/Apostrof* (każdy posuwa się od lewej do prawej, chyba, że dalej nie może - wtedy się cofa),
* Klawisze *J K L* odpowiadają za umiejętności naszych bohaterów.
* Klawisz *J* odpowiada za umiejętności na lewej pozycji:
** Wojownik podniesie tarczę (wedle założeń - póki co tylko kolor) która sprawi, ze uchroni SIEBIE od obrażeń fizycznych.
** Łotrzyk rozstawi pułapkę na przeciwników.
** Mag będzie leczył drużynę.
* Klawisz *K* odpowiada za umiejętności na środkowej pozycji:
** Wojownik podniesie morale drużyny, przez co wszyscy będą w stanie poruszać się szybciej i skakać dalej.
** Łotrzyk potrafi otworzyć skrzynię.
** Mag sprawi, że drużyna otrzyma tymczasową odporność na magiczne obrażenia.
* Klawisz *L* odpowiada za umiejętności na prawej pozycji:
** Każda postać zaatakuje.
* Klawisz *Esc* otwiera menu pauzy. 

<<<
== Przegląd sprintu (tydzień 10)

=== Edyta

* [x] Zebranie dźwięków i muzyki przydatnych w grze -> w podstawowym zakresie.
* [x] Wprowadzenie dźwięków i muzyki do gry.
* [ ] Poprawa wyglądu licznika czasu oraz zebranych skarbów -> ze względu na zamieszanie z grupami, przeniesione na następny sprint.

=== Krzysiek

* [x] Poprawa fizyki gry.
* [x] Poprawa działania kamery.
* [x] Dopracowanie SI Zombie.

=== Gracjan

* [x] Poprawa wyglądu najbardziej zastępczych assetów - tak, by nie trzeba było domyślać się/zgadywać co to jest.
* [ ] Poprawa animacji zamiany kolejności bohaterów -> prace rozpoczęte, jednak ze względu na zamieszanie z grupami nie udało się tego dokończyć.

=== Justyna

* [x] Poprawa umiejętności otwierania skrzyń.
* [x] Poprawa zbierania przedmiotów - od teraz będzie do widoczniejsze dla gracza, że podniósł rzecz, która zwiększa mu punkty.
* [x] Rozpoczęcie prac nad zwykłym, grywalnym poziomem -> razem z Karolem.

=== Bartosz
 
* [x] Bugmaster - usuwanie błędów z gry -> razem z Karolem.
** [x] Przyśpieszenie bohaterów (umiejętność rycerza) dezaktywuje się po śmierci, zamiast działać do jej ponownej aktywacji.
** [x] Leczenie (umiejętność maga) działa znowu na całą drużynę (po wprowadzeniu pasku życia na HUDzie działa tylko na rycerza)
* [x] Wprowadzenie życia dla beczki, oraz efektów związanych z jej niszczeniem.
* [x] Dodanie nowej umiejętności - zastawianie pułapek przez łotrzyka.

=== Konrad

* [x] Rozwijanie HUDu: 
** [x] Interfejs każdego bohatera zmienia sie wraz z jego zmiana pozycji
* [x] Poprawa animacji postaci przy używaniu umiejętności.
* [x] Zebranie feedbacku związanego ze zmianami w grze.

=== Zbyszek

* [x] Rozwijanie HUDu:
** [x] Opcje wybrane w ustawieniach mają wpływ na zachowanie i wygląd HUDu
** [x] Dodanie animacji na czas trwania umiejętności oraz poprawa widoczności dostępnych umiejętności.
* [x] Przeniesienie sterowania do własnego InputManagera.
* [x] Dopracowywanie działania menu gry oraz menu pauzy.
** [x] Dodane opcje dotyczące HUDu w grze.
** [x] Zlikwidowany bug, przez który gra mogła być odpauzowana przy wciąż aktywnym menu.

=== Karol

* [x] Przygotowanie kolejnej wersji dokumentu, który pozwoli zobaczyć jak przebiegała praca w sprincie i jakie mamy dalej założenia.
* [x] Połączenie zmian wprowadzonych przez team w jedną część.
* [x] Projektowanie poziomu tutorialowego - poprawki oraz naniesienie zaktualizowanych obiektów.
* [x] Rozpoczęcie prac nad zwykłym, grywalnym poziomem -> razem z Justyną.
* [x] Bugmaster - usuwanie błędów z gry -> razem z Bartoszem.
** [x] Pasek życia nie obraca się razem z bohaterami.
** [x] Umiejętności które zmieniają kolory bohaterów podczas ich trwania od teraz faktycznie zmieniają ten kolor.
** [x] Tabliczki od teraz pokazują się w zależności od średniej pozycji drużyny, a nie pozycji rycerza.
** [ ] Zamiana bohaterów nie blokuje się bez powodu na czas paru sekund -> dotarcie do sedna problemu oraz przygotowanie kodu do dalszych poprawek (ze względu na planowane zmiany w "zamianie bohaterów" dalsze inwestygowanie nie przyniosło by wymiernych korzyści względem potrzebnego czasu na rozwiązanie problemu przy obecnej implementacji)
* [x] Dodanie nowej umiejętności - tarcza dla rycerza.

<<<
== Plan sprintu (tydzień 11)

Poniżej przedstawiamy plan na sprint poprawkowy.

=== Edyta

* [ ] Poprawa wyglądu licznika czasu oraz zebranych skarbów.

=== Gracjan

* [ ] Poprawa animacji zamiany kolejności bohaterów.

<<<
== Plan sprintu (tydzień 12)

Poniżej przedstawiamy podział obowiązków na najbliższy (pełny) sprint. 

=== Edyta

* [ ] Dodanie do gry kolejnych dźwięków oraz muzyki.
* [ ] Wprowadzenie efektów związanych z uderzeniem (np w beczkę, zombie, ścianę).
* [ ] Wprowadzenie checkpointów -> razem z Gracjanem.

=== Krzysiek

* [ ] Poprawa łączenia się drużyny.
* [ ] Fizyka gry: zachowanie bohaterów na schodach/ternach pochyłych.
* [ ] Prace nad AI wrogów: szkielet, ewentualne poprawy zombie.

=== Gracjan

* [ ] Kolejne prace związane z assetami.
* [ ] Dodanie ograniczeń do zamiany bohaterów: nie można jej wykonywać m.in. w trakcie skoku, castowania umiejętności.
* [ ] Wprowadzenie checkpointów -> razem z Edytą.

=== Justyna

* [ ] Praca nad grywalnym poziomem -> razem z Karolem.
* [ ] Dodanie zakończenia poziomu.
* [ ] Wprowadzenie slotu na zbierane klucze (otwieranie skrzyni na ten moment nic nie daje - czasami musi wypadać coś ekstra poza punktami) oraz obiektów które tylko z tym kluczem działają.

=== Bartosz
 
* [ ] Bugmaster - usuwanie błędów z gry -> razem z Karolem.
* [ ] Poprawa umiejętności - zawsze działają w określoną stronę (np pułapka łotrzyka zawsze się pojawia za drużyną).
* [ ] Zmiana rozumienia kolejności - od teraz liczy się kto przewodzi drużynie, a kto jest z prawej strony.

=== Konrad

* [ ] Rozwijanie HUDu:
** [ ] Przeniesienie HUDu na dół.
** [ ] Napisy dotyczące pozycji oraz klawiszy.
** [ ] Lekkie powiększenie i wyraźniejsze oddzielenie modułów.
** [ ] Naprawienie wszelkich błędów HUDowych.
* [ ] Poprawa animacji umiejętności - dodanie brakujących, dopasowanie animacji do faktycznego czasu działania.
* [ ] Zebranie feedbacku po 12 tygodniu zajęć.

=== Zbyszek

* [ ] Rozwijanie HUDu:
** [ ] Przeniesienie HUDu na dół.
** [ ] Napisy dotyczące pozycji oraz klawiszy.
** [ ] Lekkie powiększenie i wyraźniejsze oddzielenie modułów.
** [ ] Naprawienie wszelkich błędów HUDowych.
* [ ] Rozwijanie ustawień (klawisze nie mogą się nakładać, dodanie ustawień związanych z dźwiękiem, przeniesienie opcji "życie" i "dynamiczny HUD" gdzie indziej).
* [ ] Wprowadzenie delikatniejszych efektów na pokazanie działających umiejętności niż kolorowanie bohaterów.

=== Karol

* [ ] Przygotowanie kolejnej wersji dokumentu, który pozwoli zobaczyć jak przebiegała praca w sprincie i jakie mamy dalej założenia.
* [ ] Połączenie zmian wprowadzonych przez team w jedną część.
* [ ] Praca nad poziomem tutorialowym. 
* [ ] Praca nad grywalnym poziomem -> razem z Justyną.
* [ ] Bugmaster - usuwanie błędów z gry -> razem z Bartoszem.
* [ ] Poprawa wizualna menu: nowa ikona gry, nowy rysunek związany z grą.
* [ ] Poprawa tabliczek - pokazują one aktualne klawisze, zamiast tych domyślnych (tekst nie jest wpisany na sztywno).
