= 3scape - przegląd i planowanie sprintu: *Tydzień 10*
Ancient Yaks
0.10.1, 2018-12-04
:toc:
:toc-title: Spis Treści
:version-label: Wersja
:icons: font

== Obecne założenia gry

3scape jest zręcznościowo-logiczną grą platformową, która działa na silniku Unity.

Wcielamy się w grupę trzech bohaterów, którzy tylko dzięki swoim połączonym zdolnościom są w stanie pokonywać kolejne przeszkody:

* wojownik - dysponuje on siłą, która okaże się nieoceniona nie tylko przy walce z wrogimi istotami czy niszczeniem przeszkód na drodze,
* łotrzyk - zwinne palce, spryt, zręczność czy umiejętność strzelania z łuku będą niezwykle przydatne podczas przemierzania świata pełnego zasadzek i pułapek, 
* czarodziej - wiedza oraz zdolności magiczne będą niejednokrotnie jedyną opcją ratunku dla naszych bohaterów.

Bohaterowie podróżują razem, idąc jeden za drugim. W zależności od ich ustawienia w rzędzie, dysponują oni innymi umiejętnościami, które potrafią oddziaływać ze sobą w najróżniejszy sposób. Dobre przetasowywanie naszej drużyny to klucz do sukcesu w 3scape.

=== Sterowanie

* Poruszamy się bohaterami za pomocą klawiszy *W A D*, bądź *strzałek*.
* Zmieniamy kolejność bohaterów za pomocą klawisza *Cudzysłów/Apostrof* (każdy posuwa się od lewej do prawej, chyba, że dalej nie może - wtedy się cofa),
* Klawisze *J K L* odpowiadają za umiejętności naszych bohaterów.
* Klawisz *J* odpowiada za umiejętności na lewej pozycji:
** Wojownik podniesie tarczę (wedle założeń - póki co tylko kolor) która sprawi, ze uchroni SIEBIE od obrażeń fizycznych.
** Łotrzyk rozstawi pułapkę na przeciwników.
** Mag będzie leczył drużynę.
* Klawisz *K* odpowiada za umiejętności na środkowej pozycji:
** Wojownik podniesie morale drużyny, przez co wszyscy będą w stanie poruszać się szybciej i skakać dalej.
** Łotrzyk potrafi otworzyć skrzynię.
** Mag sprawi, że drużyna otrzyma tymczasową odporność na magiczne obrażenia.
* Klawisz *L* odpowiada za umiejętności na prawej pozycji:
** Każda postać zaatakuje.
* Klawisz *Esc* otwiera menu pauzy. 

<<<
== Przegląd sprintu (tydzień 10)

=== Edyta

* [x] Zebranie dźwięków i muzyki przydatnych w grze -> w podstawowym zakresie.
* [x] Wprowadzenie dźwięków i muzyki do gry.
* [ ] Poprawa wyglądu licznika czasu oraz zebranych skarbów -> ze względu na zamieszanie z grupami, przeniesione na następny sprint.

=== Krzysiek

* [x] Poprawa fizyki gry.
* [x] Poprawa działania kamery.
* [x] Dopracowanie SI Zombie.

=== Gracjan

* [x] Poprawa wyglądu najbardziej zastępczych assetów - tak, by nie trzeba było domyślać się/zgadywać co to jest.
* [ ] Poprawa animacji zamiany kolejności bohaterów -> prace rozpoczęte, jednak ze względu na zamieszanie z grupami nie udało się tego dokończyć.

=== Justyna

* [x] Poprawa umiejętności otwierania skrzyń.
* [x] Poprawa zbierania przedmiotów - od teraz będzie do widoczniejsze dla gracza, że podniósł rzecz, która zwiększa mu punkty.
* [x] Rozpoczęcie prac nad zwykłym, grywalnym poziomem -> razem z Karolem.

=== Bartosz
 
* [x] Bugmaster -  usuwanie błędów z gry -> razem z Karolem.
** [x] Przyśpieszenie bohaterów (umiejętność rycerza) dezaktywuje się po śmierci, zamiast działać do jej ponownej aktywacji.
** [x] Leczenie (umiejętność maga) działa znowu na całą drużynę (po wprowadzeniu pasku życia na HUDzie działa tylko na rycerza)
* [x] Wprowadzenie życia dla beczki, oraz efektów związanych z jej niszczeniem.
* [x] Dodanie nowej umiejętności - zastawianie pułapek przez łotrzyka.

=== Konrad

* [x] Rozwijanie HUDu. 
** [x] Interfejs każdego bohatera zmienia sie wraz z jego zmiana pozycji
* [x] Poprawa animacji postaci przy używaniu umiejętności.
* [x] Zebranie feedbacku związanego ze zmianami w grze.

=== Zbyszek

* [x] Rozwijanie HUDu. 
** [x] Opcje wybrane w ustawieniach mają wpływ na zachowanie i wygląd HUDu
** [x] Dodanie animacji na czas trwania umiejętności oraz poprawa widoczności dostępnych umiejętności.
* [x] Przeniesienie sterowania do własnego InputManagera.
* [x] Dopracowywanie działania menu gry oraz menu pauzy.
** [x] Dodane opcje dotyczące HUDu w grze.
** [x] Zlikwidowany bug, przez który gra mogła być odpauzowana przy wciąż aktywnym menu.

=== Karol

* [x] Przygotowanie kolejnej wersji dokumentu, który pozwoli zobaczyć jak przebiegała praca w sprincie i jakie mamy dalej założenia.
* [x] Połączenie zmian wprowadzonych przez team w jedną część.
* [x] Projektowanie poziomu tutorialowego - poprawki oraz naniesienie zaktualizowanych obiektów.
* [x] Rozpoczęcie prac nad zwykłym, grywalnym poziomem -> razem z Justyną.
* [x] Bugmaster - usuwanie błędów z gry -> razem z Bartoszem.
** [x] Pasek życia nie obraca się razem z bohaterami.
** [x] Umiejętności które zmieniają kolory bohaterów podczas ich trwania od teraz faktycznie zmieniają ten kolor.
** [x] Tabliczki od teraz pokazują się w zależności od średniej pozycji drużyny, a nie pozycji rycerza.
** [x] Zamiana bohaterów nie blokuje się bez powodu na czas paru sekund -> dotarcie do sedna problemu, usprawnienie działania (nie całkowite wyeliminowanie) oraz przygotowanie kodu do dalszych poprawek (ze względu na planowane zmiany w "zamianie bohaterów" dalsze inwestygowanie nie przyniosło by wymiernych korzyści wzgledem potrzebnego czasu na rozwiązanie problemu przy obecnej implementacji )
* [x] Dodanie nowej umiejętności - tarcza dla rycerza.

<<<
== Plan sprintu (tydzień 12)

Poniżej przedstawiamy podział obowiązków na najbliższy sprint. 

=== Cały zespół

Są to zadania wewnętrzne, które mają ułatwić pracę nad projektem - nie są one przeznaczone ocenie podczas ewaluacji z prowadzącymi.

* [ ] _

=== Edyta

* [ ] _

=== Krzysiek

* [ ] Poprawa fizyki gry.
* [ ] _

=== Gracjan

* [ ] _

=== Justyna

* [ ] Praca nad grywalnym poziomem -> razem z Karolem.
* [ ] _

=== Bartosz
 
* [ ] _

=== Konrad

* [ ] Rozwijanie HUDu. 
* [ ] Zebranie feedbacku po 10 tygodniu zajęć.
* [ ] _

=== Zbyszek

* [ ] Rozwijanie HUDu. 
* [ ] _

=== Karol

* [ ] Przygotowanie kolejnej wersji dokumentu, który pozwoli zobaczyć jak przebiegała praca w sprincie i jakie mamy dalej założenia.
* [ ] Połączenie zmian wprowadzonych przez team w jedną część.
* [ ] Projektowanie poziomu tutorialowego - wprowadzanie prostych przeszkód pozwalających pokazać zdolności bohaterów i objaśniających jak działa gra. 
* [ ] Praca nad grywalnym poziomem -> razem z Justyną.
* [ ] _

=== Rzeczy dodatkowe

* [ ] Fabuła gry.
* [ ] _