= 3scape - przegląd i planowanie sprintu: *Tydzień 14*
Ancient Yaks
0.14.1, 2018-01-15
:toc:
:toc-title: Spis Treści
:version-label: Wersja
:icons: font

== Obecne założenia gry

3scape jest zręcznościowo-logiczną grą platformową, która działa na silniku Unity.

Wcielamy się w grupę trzech bohaterów, którzy tylko dzięki swoim połączonym zdolnościom są w stanie pokonywać kolejne przeszkody:

* wojownik - dysponuje on siłą, która okaże się nieoceniona nie tylko przy walce z wrogimi istotami czy niszczeniem przeszkód na drodze,
* łotrzyk - zwinne palce, spryt, zręczność czy umiejętność strzelania z łuku będą niezwykle przydatne podczas przemierzania świata pełnego zasadzek i pułapek, 
* czarodziej - wiedza oraz zdolności magiczne będą niejednokrotnie jedyną opcją ratunku dla naszych bohaterów.

Bohaterowie podróżują razem, idąc jeden za drugim. W zależności od ich ustawienia w rzędzie, dysponują oni innymi umiejętnościami, które potrafią oddziaływać ze sobą w najróżniejszy sposób. Dobre przetasowywanie naszej drużyny to klucz do sukcesu w 3scape.

=== Sterowanie

* Poruszamy się bohaterami za pomocą klawiszy *W A D*, bądź *strzałek*.
* Zmieniamy kolejność bohaterów za pomocą *Spacji* (każdy posuwa się od lewej do prawej, chyba, że dalej nie może - wtedy się cofa),
* Klawisze *J K L* odpowiadają za umiejętności naszych bohaterów.
* Klawisz *J* odpowiada za umiejętności na lewej pozycji:
** Wojownik podniesie tarczę (wedle założeń - póki co tylko kolor) która sprawi, ze uchroni SIEBIE od obrażeń fizycznych.
** Łotrzyk rozstawi pułapkę na przeciwników.
** Mag będzie leczył drużynę.
* Klawisz *K* odpowiada za umiejętności na środkowej pozycji:
** Wojownik podniesie morale drużyny, przez co wszyscy będą w stanie poruszać się szybciej i skakać dalej.
** Łotrzyk potrafi otworzyć skrzynię.
** Mag sprawi, że drużyna otrzyma tymczasową odporność na magiczne obrażenia.
* Klawisz *L* odpowiada za umiejętności na prawej pozycji:
** Każda postać zaatakuje.
* Klawisz *Esc* otwiera menu pauzy. 

<<<
== Przegląd sprintu (tydzień 14)

Poniżej przedstawiamy podział obowiązków na ostatni sprint. 

=== Edyta

* [x] Dokończenie checkpointów.
* [x] Nowa muzyka: menu, ustawienia, creditsy, 2 poziom.
* [x] Poprawa efektów dźwiękowych: otwieranie skrzyni łotrzyka, muzyka w tutorialu.
* [x] Dodać ekran ładowania.

=== Krzysiek

* [x] Zablokować łącznie się postaci.
* [x] Poprawienie colliderów (wciąż możliwe stanie na wrogach).
* [x] Poprawa AI bossa (podczas skakania drużyna staje się dla niego niewidoczna).

=== Gracjan

* [x] Zmiana bohaterów na dwóch klawiszach -> zmiana nie ujęta w finalnym buildzie. Gracze którzy zaproponowali taką zmianę po zobaczeniu jej wpływu na grę sami stwierdzili, że nie wpływa to dobrze, zostaliśmy więc przy starym rozwiązaniu z jednym klawiszem.
* [ ] Wprowadzenie przeciwnika - szkieleta łucznika.
* [x] Rozwój bossa: wprowadzenie paska życia, blokada ukończenia poziomu do póki boss nie zostanie pokonany, większa mobilność.
* [x] Zmienić ikonę pola ochronnego.

=== Justyna

* [x] Stworzenie 2 poziomu. 
* [x] Poprawki w 1 poziomie: niezniszczalna beczka.

=== Bartosz
 
* [x] link:http://bambit.com.pl/3scape[Strona internetowa].

=== Konrad

* [x] Wyszarzenie samych ikon umiejętności, a nie całych slotów.
* [x] Timery umiejętności: ile jeszcze działają, ile się ładują.
* [x] Wprowadzenie specjalnego miejsca na klucz.
* [x] Poprawa czytelności HUDu: ilość trapów oraz slot na klucz na dół, lepiej pokazany czas oraz punkty na górze.

=== Zbyszek

* [x] Stworzenie planszy końcowej po poziomie.
* [x] Licznik dla możliwych do postawienia / postawionych bomb.
* [x] Dodana autodestrukcja do obiektów tworzonych przez gracza: pułapki, strzały/pociski magiczne.

=== Karol

* [x] Przygotowanie kolejnej wersji dokumentu, który pozwoli zobaczyć jak przebiegała praca w sprincie i jakie mamy dalej założenia.
* [x] Połączenie zmian wprowadzonych przez team w jedną część.
* [x] Dostosowanie wyglądu ustawień do wyglądu menu.
* [x] Dodane credity do gry.